# Generated by Django 2.1.5 on 2019-12-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='document_id',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_annotation', to='label.Document'),
        ),
        migrations.AlterField(
            model_name='label',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_label', to='label.Project'),
        ),
    ]
