# Generated by Django 2.1.5 on 2020-01-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20191223_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='document_id',
        ),
        migrations.AddField(
            model_name='document',
            name='annotation',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AddField(
            model_name='document',
            name='is_checked',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
