# Generated by Django 2.1.5 on 2020-01-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_auto_20200102_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='annotation',
        ),
        migrations.AddField(
            model_name='document',
            name='annotations',
            field=models.CharField(default='[[]]', max_length=2048),
        ),
    ]
