# Generated by Django 2.1.5 on 2020-01-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_document_predications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='predications',
            field=models.CharField(default='[[]]', max_length=4096),
        ),
    ]
