# Generated by Django 2.1.5 on 2020-01-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_auto_20200103_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='predications',
            field=models.TextField(default='[[]]'),
        ),
    ]
